apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "web.servers.org/v1alpha1",
          "kind": "JBossWebServer",
          "metadata": {
            "name": "example-jbosswebserver"
          },
          "spec": {
            "applicationImage": "registry.redhat.io/jboss-webserver-5/webserver53-openjdk8-tomcat9-openshift-rhel7:latest",
            "applicationName": "jws-app",
            "replicas": 2
          }
        },
        {
          "apiVersion": "web.servers.org/v1alpha1",
          "kind": "JBossWebServer",
          "metadata": {
            "name": "example-jbosswebserver"
          },
          "spec": {
            "applicationName": "jws-app",
            "artifactDir": "",
            "contextDir": "tomcat-websocket-chat",
            "genericWebhookSecret": "tomcat",
            "githubWebhookSecret": "tomcat",
            "imageStreamName": "jboss-webserver53-tomcat9-openshift:latest",
            "imageStreamNamespace": "openshift",
            "jwsAdminPassword": "tomcat",
            "jwsAdminUsername": "tomcat",
            "mavenMirrorUrl": "",
            "replicas": 2,
            "serverReadinessScript": "/bin/bash -c \"/usr/bin/curl --noproxy '*' -s -u ${JWS_ADMIN_USERNAME}:${JWS_ADMIN_PASSWORD} 'http://localhost:8080/manager/jmxproxy/?get=Catalina%3Atype%3DServer\u0026att=stateName' | /usr/bin/grep -iq 'stateName *= *STARTED'\"",
            "sourceRepositoryRef": "1.2",
            "sourceRepositoryUrl": "https://github.com/jboss-openshift/openshift-quickstarts.git"
          }
        }
      ]
    capabilities: Basic Install
  name: jws-image-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: JBossWebServer is the Schema for the jbosswebservers API
      kind: JBossWebServer
      name: jbosswebservers.jwsservers.web.servers.org
      version: v1alpha1
    - description: JBossWebServer is the Schema for the jbosswebservers API
      kind: JBossWebServer
      name: jwsservers.web.servers.org
      version: v1alpha1
  displayName: Jws Image Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - imagestreams
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - image.openshift.io
          resources:
          - imagestreams
          verbs:
          - '*'
        - apiGroups:
          - build.openshift.io
          resources:
          - buildconfigs
          verbs:
          - '*'
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - jws-image-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - web.servers.org
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - services/finalizers
          verbs:
          - update
        serviceAccountName: jws-image-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 0.1.0
