apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jbosswebservers.jwsservers.web.servers.org
spec:
  group: jwsservers.web.servers.org
  names:
    kind: JBossWebServer
    listKind: JBossWebServerList
    plural: jbosswebservers
    singular: jbosswebserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: JBossWebServer is the Schema for the jbosswebservers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: JBossWebServerSpec defines the desired state of JBossWebServer
          properties:
            applicationImage:
              description: ApplicationImage is the name of the application image to
                be deployed
              type: string
            applicationName:
              type: string
            artifactDir:
              type: string
            contextDir:
              type: string
            genericWebhookSecret:
              type: string
            githubWebhookSecret:
              type: string
            imageStreamName:
              type: string
            imageStreamNamespace:
              type: string
            jwsAdminPassword:
              type: string
            jwsAdminUsername:
              description: Username and Password are for pre 5.4 images
              type: string
            mavenMirrorUrl:
              type: string
            replicas:
              description: Replicas is the desired number of replicas for the application
              format: int32
              type: integer
            serverLivenessScript:
              type: string
            serverReadinessScript:
              description: Corresponding Strings from the health check logics
              type: string
            sourceRepositoryRef:
              type: string
            sourceRepositoryUrl:
              type: string
          required:
          - applicationImage
          - applicationName
          - artifactDir
          - contextDir
          - genericWebhookSecret
          - githubWebhookSecret
          - imageStreamName
          - imageStreamNamespace
          - jwsAdminPassword
          - jwsAdminUsername
          - mavenMirrorUrl
          - replicas
          - serverLivenessScript
          - serverReadinessScript
          - sourceRepositoryRef
          - sourceRepositoryUrl
          type: object
        status:
          description: JBossWebServerStatus defines the observed state of JBossWebServer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
