# permissions for end users to view webservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webserver-viewer-role
rules:
- apiGroups:
  - web.servers.org
  resources:
  - webservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.servers.org
  resources:
  - webservers/status
  verbs:
  - get
