apiVersion: apps/v1
kind: Deployment
metadata:
  name: jws-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jws-operator
  template:
    metadata:
      labels:
        name: jws-operator
    spec:
      serviceAccountName: jws-operator
      containers:
        - name: jws-operator
          image: registry.redhat.io/jboss-webserver-5/webserver-openjdk8-rhel8-operator@sha256:e3fff4fecf05e350c32fffc63ea548f8e4628412fd000b4c90095a84806f61d0
          command:
            - jws-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jws-operator"
