kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jws-operator
subjects:
  - kind: ServiceAccount
    name: jws-operator
roleRef:
  kind: Role
  name: jws-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jws-operator-view
subjects:
  - kind: ServiceAccount
    name: jws-operator
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
