apiVersion: web.servers.org/v1alpha1
kind: WebServer
metadata:
  name: example-imagestream-sources-webserver
spec:
  # Add fields here
  applicationName: jws-app
  replicas: 2
  webImageStream:
    imageStreamNamespace: openshift
    imageStreamName: jboss-webserver56-openjdk8-tomcat9-openshift-ubi8
    webSources:
      sourceRepositoryUrl: https://github.com/jfclere/demo-webapp
      # sourceRepositoryUrl: https://github.com/jboss-openshift/openshift-quickstarts.git
      # sourceRepositoryRef: "1.2"
      # contextDir: tomcat-websocket-chat
