apiVersion: web.servers.org/v1alpha1
kind: WebServer
metadata:
  name: example-imagestream-webserver
spec:
  # Add fields here
  applicationName: jws-app
  replicas: 2
  webImageStream:
    imageStreamNamespace: openshift
    imageStreamName: jboss-webserver56-openjdk8-tomcat9-openshift-ubi8
